-- View Database to analyse
select * from customer limit 5

-- Q1. Calculate and compare the total revenue generated by male and female customers.
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


-- Q2. Identify customers who used a discount yet spent more than the overall average purchase amount.
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Retrieve the top 5 products with the highest average review rating.
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5


-- Q4. Compare the average purchase amount between Standard and Express shipping methods.
select shipping_type ,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type


-- Q5. Evaluate whether subscribed customers spend more by comparing average spend and total revenue against non-subscribers.
select subscription_status,
		COUNT(customer_id) as total_customers,
		ROUND(AVG(purchase_amount),2) as avg_spend,
		ROUND(SUM (purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


-- Q6. Identify the products with the highest proportion of purchases where a discount was applied.
select item_purchased,
		ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


-- Q7. Classify customers as New, Returning, or Loyal based on their number of previous purchases, and return the count in each segment.
with customer_type as (
	select customer_id, previous_purchases,
	CASE
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment


-- Q8. For each category, list the top 3 most frequently purchased products.
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3


-- Q9. Assess whether customers with more than 5 previous purchases are more likely to be subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status



-- Q10. Calculate the revenue contribution of each age group.
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc
